CREATE TABLE transfer_certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    admission_no VARCHAR(100) NOT NULL,
    class_level VARCHAR(100) NOT NULL,
    section VARCHAR(50) NOT NULL,
    father_name VARCHAR(255) NOT NULL,
    aadhar_no VARCHAR(100) NOT NULL,
    tc_number VARCHAR(100) NOT NULL,
    issue_date TIMESTAMP NOT NULL,
    pdf_url VARCHAR(512),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_tc_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
