CREATE TABLE site_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    path VARCHAR(512),
    visited_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_site_visits_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);

CREATE INDEX idx_site_visits_tenant_time ON site_visits (tenant_id, visited_at);
