CREATE TABLE student_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    subject_name VARCHAR(255) NOT NULL,
    term VARCHAR(100) NOT NULL,
    grade VARCHAR(50) NOT NULL,
    remarks VARCHAR(512),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_student_grades_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE
);
